
data:
  batch_size: 64
  num_workers: 10
  class_column: subject_
  path_column: vast_png_path
  target_crop_size: [420, 600]
  subsample_factor: [3, 3]
  extra_column_outputs: 
    - sensor_serial
    - subject_
    - selected_power
    - placement_ind
    - wiggle_ind

  train:
    update_train_data: false
    name: train
    is_train: true
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_train_v14_removed_test_data.pkl
    batch_size: ${data.batch_size}
    class_column: ${data.class_column}
    path_column: ${data.path_column}
    target_crop_size: ${data.target_crop_size}
    subsample_factor: ${data.subsample_factor}
    extra_column_outputs: ${data.extra_column_outputs}
    transforms:
      ColorJitter:
        brightness: 0.1
        contrast: 0.1
      RandomHorizontalFlip: 0.5
      RandomVerticalFlip: 0.5
      RandomRotation: 2
      RandomPerspective: 0.15
      RandomResizedCrop:
        scale: [0.8, 1.12]
        size: [224, 224]
      RandomErasing: 0.1
    epoch_len: 100
  val:
    name: validation
    is_train: false
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_val_for_TB_v0.pkl
    batch_size: ${data.batch_size}
    class_column: ${data.class_column}
    path_column: ${data.path_column}
    target_crop_size: ${data.target_crop_size}
    subsample_factor: ${data.subsample_factor}
    extra_column_outputs: ${data.extra_column_outputs}
    transforms:
      Resize: [224, 224]
  test:
    name: test
    is_train: false
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_test_for_TB_v0.pkl
    batch_size: ${data.batch_size}
    class_column: ${data.class_column}
    path_column: ${data.path_column}
    target_crop_size: ${data.target_crop_size}
    subsample_factor: ${data.subsample_factor}
    extra_column_outputs: ${data.extra_column_outputs}
    transforms:
      Resize: [224, 224]

model:
  lr_config:
    learning_rate: 5.0e-06
    lr_scheduler_kwargs: 
      lower_bound_lr: 1.64e-4
      step_size: 80
      gamma: 0.8
    lr_scheduler_has_monitor: False

  embedding_size: 512
  pretrained_model_name: efficientnet_b3
  unpg:
    margin: 0.04
    wisk: 0.5
  init_centroids: true
  train_centroids: false


trainer:
  epochs: 4000
  exps_dir: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/V2/
  monitor: approx_test_acc
  monitor_mode: max
  exp_name: crop_420x600__subsample_3x3__less_aug__${model.pretrained_model_name}_fixed_split

analysis:
  dataset:
    name: full_test_set
    is_train: false
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_test_v0.pkl
    batch_size: ${data.batch_size}
    class_column: ${data.class_column}
    path_column: ${data.path_column}
    target_crop_size: ${data.target_crop_size}
    subsample_factor: ${data.subsample_factor}
    extra_column_outputs: ${data.extra_column_outputs}
    transforms:
      Resize: [224, 224]
  k_top_models_to_analyze: 5
  monitor: ${trainer.monitor}
  monitor_mode: ${trainer.monitor_mode}

pipeline_stages:
  - train
  - analysis