defaults:
  - override hydra/launcher: submitit_slurm 

data:
  batch_size: 64
  num_workers: 10
  class_column: subject_
  path_column: vast_png_path
  target_crop_size: [420, 600]
  subsample_factor: [3, 3]
  extra_column_outputs: 
    - sensor_serial
    - subject_
    - selected_power
    - placement_ind
    - wiggle_ind

  train:
    update_train_data: false
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_train_v14_removed_test_data.pkl
    transforms:
      ColorJitter:
        brightness: 0.1
        contrast: 0.1
      RandomHorizontalFlip: 0.5
      RandomVerticalFlip: 0.5
      RandomRotation: 2
      RandomPerspective: 0.15
      RandomResizedCrop:
        scale: [0.8, 1.12]
        size: [224, 224]
      RandomErasing: 0.1
    epoch_len: 100
  val:
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_val_for_TB_v0.pkl
    transforms:
      Resize: [224, 224]
  test:
    df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_test_for_TB_v0.pkl
    transforms:
      Resize: [224, 224]

model:
  lr_config:
    learning_rate: 5.0e-06
    lr_scheduler_kwargs: 
      lower_bound_lr: 1.64e-4
      step_size: 80
      gamma: 0.8
    lr_scheduler_has_monitor: False

  embedding_size: 512
  pretrained_model_name: efficientnet_b3
  unpg:
    margin: 0.04
    wisk: 0.5
  init_centroids: true
  train_centroids: false


trainer:
  epochs: 4000
  exps_dir: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/V2
  monitor: approx_test_acc
  monitor_mode: max
  exp_name: crop_420x600__subsample_3x3__less_aug__${model.pretrained_model_name}__LR_${model.lr_config.learning_rate}__Brightness_${data.train.transforms.ColorJitter.brightness}__Contrast_${data.train.transforms.ColorJitter.contrast}

analysis:
  df_file: /mnt/ML/ModelsTrainResults/shlomi.fenster/PixelsBioID/meta_data_dfs/split_16Dec2024_test_v0.pkl
  k_top_models_to_analyze: 5


hydra:
  sweep:
    dir: ${exps_dir}/${exp_name}
    subdir: hp_search
  sweeper:
    params:  
      model.lr_config.learning_rate: 1.0e-06, 1.0e-05, 1.0e-04
      data.train.transforms.ColorJitter.brightness: 0.1, 0.2
      data.train.transforms.ColorJitter.contrast: 0.1, 0.2

  launcher:
    cpus_per_task: 12
    mem_gb: 160
    partition: A6000_L40S_VAST
    gpus_per_task: 1
    tasks_per_node: 1 
    timeout_min: 20000
    qos: normal
    array_parallelism: 16  # Maximal number of tasks in parallel

